# Generated by Django 5.2 on 2025-07-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': ('Categoría de respuesta',),
                'verbose_name_plural': ('Categorías de respuesta',),
            },
        ),
        migrations.CreateModel(
            name='PossibleAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='Respuesta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.categoryanswer')),
            ],
            options={
                'verbose_name': ('Posible respuesta',),
                'verbose_name_plural': 'Posibles respuestas',
            },
        ),
    ]
