# Generated by Django 5.2 on 2025-07-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_categoryanswer_possibleanswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryanswer',
            options={'verbose_name': 'Categoría de respuesta', 'verbose_name_plural': 'Categorías de respuesta'},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.categoryanswer')),
            ],
            options={
                'verbose_name': ('Pregunta',),
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
