# Generated by Django 5.2 on 2025-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_categoryanswer_options_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryanswer',
            options={'verbose_name': 'Carga de Embeddings', 'verbose_name_plural': 'Carga de Embeddings'},
        ),
        migrations.RemoveField(
            model_name='categoryanswer',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryanswer',
            name='document',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categoryanswer',
            name='label',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PossibleAnswers',
        ),
    ]
