# Generated by Django 5.2 on 2025-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_categoryanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(default='')),
                ('label', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Carga de Embeddings',
                'verbose_name_plural': 'Carga de Embeddings',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryanswer',
            options={'verbose_name': 'Categoría de respuesta', 'verbose_name_plural': 'Categorías de respuesta'},
        ),
        migrations.RemoveField(
            model_name='categoryanswer',
            name='document',
        ),
        migrations.RemoveField(
            model_name='categoryanswer',
            name='label',
        ),
        migrations.AddField(
            model_name='categoryanswer',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='Categoría'),
        ),
    ]
