# Generated by Django 5.2.4 on 2025-07-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_possibleanswer_alter_categoryanswer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PossibleAnswer',
        ),
    ]
