# Generated by Django 5.2 on 2025-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='management_type',
            field=models.CharField(choices=[('public', 'Publica'), ('private', 'Privada')], max_length=20, null=True, verbose_name='Tipo de gestión'),
        ),
    ]
