# Generated by Django 5.2 on 2025-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('university', 'Universidad'), ('institute', 'Instituto')], default='university', max_length=20, verbose_name='Tipo de institución'),
        ),
    ]
