# Generated by Django 5.2 on 2025-06-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_management_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
