# Generated by Django 5.2 on 2025-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_area_career_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='areas'),
        ),
        migrations.AlterField(
            model_name='career',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='careers'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos', verbose_name='Logo'),
        ),
    ]
